#!/usr/bin/env bash

# dependencies setup
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y tmux vim git-core zsh
apt-get install -y build-essential cmake python-dev python-3-dev

# todo: node, ruby


# dotfiles setup

#DOTFILES=$(dirname $0)
#if [ -z $1 ]; then
#  TARGET_HOME=$HOME
#else
#  TARGET_HOME=$1
#fi
#
#ln -s $DOTFILES/oh-my-zsh $TARGET_HOME/.oh-my-zsh
#ln -s $DOTFILES/zsh/* $TARGET_HOME/.oh-my-zsh/custom
#$TARGET_HOME/.oh-my-zsh/tools/install.sh
#
#ln -s $DOTFILES/vimrc $TARGET_HOME/.vimrc
#ln -s $DOTFILES/vim $TARGET_HOME/.vim
#ln -s $DOTFILES/tmux.conf $TARGET_HOME/.tmux.conf
#
#ln -s $DOTFILES/fzf $TARGET_HOME/.fzf
#$TARGET_HOME/.fzf/install
#
#cd $TARGET_HOME/.vim/bundle/vimproc.vim
#make
#
#cd $TARGET_HOME/vim/bundle/YouCompleteMe
#./install.py --tern-completer
