#!/usr/bin/env bash

if [ -z $1 ]; then
  TARGET_HOME=$HOME
else
  TARGET_HOME=$1
fi


# node
set -ex \
  && for key in \
    9554F04D7259F04124DE6B476D5A82AC7E37093B \
    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    0034A06D9D9B0064CE8ADF6BF1747F4AD2306D93 \
    FD3A5288F042B6850C66B31F09FE44734EB7990E \
    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    B9AE9905FFD7803F25714661B63B535A4C206CA9 \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
  ; do \
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
  done

NODE_VERSION=6.3.0
NODE_DIR=$TARGET_HOME/.node
mkdir $NODE_DIR

curl -sSLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" \
  && curl -sSLO "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
  && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
  && grep " node-v$NODE_VERSION-linux-x64.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
  && tar -xJf "node-v$NODE_VERSION-linux-x64.tar.xz" -C $NODE_DIR --strip-components=1 \
  && rm "node-v$NODE_VERSION-linux-x64.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt

mkdir -p $TARGET_HOME/bin
ln -s $NODE_DIR/bin/node $TARGET_HOME/bin/node
ln -s $NODE_DIR/bin/npm $TARGET_HOME/bin/npm

# ruby (todo)

# dotfiles setup

DOTFILES=/vagrant

cp -r $DOTFILES/oh-my-zsh $TARGET_HOME/.oh-my-zsh
cp $DOTFILES/zsh/custom/*.zsh $TARGET_HOME/.oh-my-zsh/custom
cp $DOTFILES/zsh/themes/*.zsh-theme $TARGET_HOME/.oh-my-zsh/themes
cp $DOTFILES/zshrc $TARGET_HOME/.zshrc

cp $DOTFILES/vimrc $TARGET_HOME/.vimrc
cp -r $DOTFILES/vim $TARGET_HOME/.vim
cp $DOTFILES/tmux.conf $TARGET_HOME/.tmux.conf

cp -r $DOTFILES/fzf $TARGET_HOME/.fzf
$TARGET_HOME/.fzf/install

cd $TARGET_HOME/.vim/bundle/vimproc.vim
make

cd $TARGET_HOME/.vim/bundle/YouCompleteMe
./install.py --tern-completer
